### ISSUE TITLE
 write a team member goal and responsibilities 

### ISSUE THREAD

**Issue by y-alhawiti** [uu-agile/hear-yourself#20]
Sustainability & regulations
Manufacturing & design, materials
Digital realm
Communications

**Comment by j-lyman** [comment]
So we're on the same page, I suggest we both formulate our Milestone Contracts accepting that the main deliverable for milestone 1 will be an **integrated management plan** (IMP). Let's phrase our individual milestones in how they relate to the following outline for a basic IMP:
![milestone-1-deliverables](https://user-images.githubusercontent.com/70165952/92960157-59c35a00-f42a-11ea-8945-c79e0863b5e6.PNG)
