### ISSUE TITLE
Preliminary Requirements Outline

### ISSUE THREAD

**Issue by y-alhawiti** [uu-agile/hear-yourself#25]
at least on RQMT /Feature

**Comment by j-lyman** [comment]
(there are 5 outlined in our [Project Overview](https://docs.google.com/document/d/1-_kNdi7-OWTZVTe0OQKmf28vq7AZkb_5JiGtElK6T1A/edit))
* Flexibility of inputs/outputs
* Sys. shall be able to broadcast to at most 15 devices
* Reduction of cable clutter
* Basic mixing capabilities on-device
* Flexibility of power source
* Built-in solar panels

**Comment by j-lyman** [comment]
Make sure you complete this outline in the [Pending Tasks Document](https://docs.google.com/document/d/1u0I8yCEycu-5_t-sYbcoqhxzkmX4sp7iZglkNR1VynM/edit)
