### ISSUE TITLE
Component Identification - Volume Control, Basic Mixing

### ISSUE THREAD

**Issue by j-lyman** [uu-agile/hear-yourself#31]
Mapping function to physical component: What components are used to achieve volume control, switching between mono/stereo operation, and controlling L/R balance in stereo output?

**Comment by sawaizzaka** [comment]
What kind of requirements?

**Comment by j-lyman** [comment]
System requirements, which will then be translated into functions, and then into physical components. This is the Systems Engineering Process. I recommend you read [this chapter](https://drive.google.com/file/d/1Um1LtTahvjwzVq1U21aheCFFFaDvUM8N/view?usp=sharing) from the SE textbook we are following to understand the fundamentals of the process.
