### ISSUE TITLE
Technical Description of System

### ISSUE THREAD

**Issue by y-alhawiti** [uu-agile/hear-yourself#39]

**Comment by j-lyman** [comment]
From Joe Jenney's [book](https://drive.google.com/drive/folders/1QANjfid2DFZT40LFhH_OzsWagaKswQ7Y?usp=sharing), the Technical description should describe the intended function and include a top level System Breakdown Structure (SBS).

SBS is described by [IEEE 1220-2005](https://drive.google.com/file/d/1pRpGRYbIou-nkz6GSu3rVYoc3fwKq7Wl/view?usp=sharing) as:

![image](https://user-images.githubusercontent.com/70165952/100012090-f3df4100-2d8f-11eb-96a1-27f9a340a9f1.png)

**Comment by j-lyman** [comment]
Also from IEEE 1220:
![image](https://user-images.githubusercontent.com/70165952/100012839-276e9b00-2d91-11eb-933f-25b25567e826.png)
